"""k-anonymity, distinct l-diversity, and categorical t-closeness analysis."""

from __future__ import annotations

import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from tabulate import tabulate

QI_COLS = ["age", "gender", "zip_code", "marital_status"]
SENSITIVE_COL = "diagnosis_name"
K_VALUES = [3, 5, 10]


def generalize_age(age: int | float, k: int) -> str:
    width = 10 if k <= 3 else 20
    low = (int(age) // width) * width
    return f"{low}-{low + width - 1}"


def generalize_zip(zip_code: object, k: int) -> str:
    value = str(zip_code).split(".")[0].zfill(5)
    # US ZIPs generated by Faker are almost unique. A publishable cohort needs
    # a coarser geography hierarchy than the guide's 3-digit prefix.
    visible = 1 if k <= 3 else 0
    return value[:visible] + "X" * (5 - visible)


def generalize_marital(status: object, k: int) -> str:
    return "Any"


def apply_k_anonymity(df: pd.DataFrame, k: int) -> tuple[pd.DataFrame, int]:
    required = ["patient_id", *QI_COLS, SENSITIVE_COL, "severity", "is_chronic"]
    missing = set(required) - set(df.columns)
    if missing:
        raise ValueError(f"Missing columns for anonymization: {sorted(missing)}")
    anon = df[required].copy()
    anon["age"] = anon["age"].map(lambda value: generalize_age(value, k))
    anon["zip_code"] = anon["zip_code"].map(lambda value: generalize_zip(value, k))
    anon["marital_status"] = anon["marital_status"].map(lambda value: generalize_marital(value, k))
    sizes = anon.groupby(QI_COLS, dropna=False, observed=True)["patient_id"].transform("size")
    suppressed = sizes < k
    anon["suppressed"] = suppressed
    anon.loc[suppressed, QI_COLS + [SENSITIVE_COL]] = "*"
    return anon, int(suppressed.sum())


def enforce_l_diversity(anon: pd.DataFrame, l: int = 2) -> tuple[pd.DataFrame, int]:
    """Suppress entire retained classes that fail distinct l-diversity."""
    output = anon.copy()
    valid = output[SENSITIVE_COL].ne("*")
    diversity = output.loc[valid].groupby(QI_COLS, observed=True)[SENSITIVE_COL].transform("nunique")
    failing_indices = diversity.index[diversity < l]
    output.loc[failing_indices, QI_COLS + [SENSITIVE_COL]] = "*"
    output.loc[failing_indices, "suppressed"] = True
    return output, int(output["suppressed"].sum())


def enforce_t_closeness(anon: pd.DataFrame, t: float = 0.3) -> tuple[pd.DataFrame, int]:
    """Iteratively suppress classes whose categorical distance exceeds t."""
    output = anon.copy()
    for _ in range(10):
        valid = output[SENSITIVE_COL].ne("*")
        if not valid.any():
            break
        global_dist = output.loc[valid, SENSITIVE_COL].value_counts(normalize=True)
        violating_indices: list[int] = []
        for _, group in output.loc[valid].groupby(QI_COLS, observed=True):
            local_dist = group[SENSITIVE_COL].value_counts(normalize=True)
            if categorical_distance(local_dist, global_dist) > t:
                violating_indices.extend(group.index.tolist())
        if not violating_indices:
            break
        output.loc[violating_indices, QI_COLS + [SENSITIVE_COL]] = "*"
        output.loc[violating_indices, "suppressed"] = True
    return output, int(output["suppressed"].sum())


def compute_ncp(original: pd.DataFrame, anonymized: pd.DataFrame) -> float:
    """Compute a bounded, hierarchy-aware normalized certainty penalty."""
    suppressed = anonymized["suppressed"] if "suppressed" in anonymized else anonymized[SENSITIVE_COL].eq("*")
    suppression_loss = float(suppressed.mean())
    valid = ~suppressed
    if not valid.any():
        return 1.0
    overall_age_range = max(1.0, float(original["age"].max() - original["age"].min()))
    age_ranges = anonymized.loc[valid, "age"].str.extract(r"^(\d+)-(\d+)$").astype(float)
    age_loss = float(((age_ranges[1] - age_ranges[0]) / overall_age_range).mean())
    zip_loss = float(anonymized.loc[valid, "zip_code"].str.count("X").mean() / 5.0)
    marital_loss = float(anonymized.loc[valid, "marital_status"].eq("Any").mean())
    gender_loss = 0.0
    generalized_loss = np.mean([age_loss, zip_loss, marital_loss, gender_loss])
    return round(float(suppression_loss + (1 - suppression_loss) * generalized_loss), 4)


def check_l_diversity(anon_df: pd.DataFrame, l: int) -> dict[str, object]:
    valid = anon_df[anon_df[SENSITIVE_COL] != "*"]
    diversity = valid.groupby(QI_COLS, dropna=False, observed=True)[SENSITIVE_COL].nunique()
    total = len(diversity)
    violating = int((diversity < l).sum()) if total else 0
    return {
        "l_value": l,
        "l_satisfied": bool(total > 0 and violating == 0),
        "total_classes": total,
        "violating_classes": violating,
        "l_satisfaction_%": round((total - violating) / total * 100, 2) if total else 0.0,
    }


def categorical_distance(p: pd.Series, q: pd.Series) -> float:
    values = p.index.union(q.index)
    return float(sum(abs(float(p.get(v, 0)) - float(q.get(v, 0))) for v in values) / 2)


def check_t_closeness(anon_df: pd.DataFrame, t: float) -> dict[str, object]:
    valid = anon_df[anon_df[SENSITIVE_COL] != "*"]
    if valid.empty:
        return {"t_value": t, "total_classes": 0, "violating_classes": 0, "t_satisfied": False, "max_emd_distance": 0.0, "t_satisfaction_%": 0.0}
    global_dist = valid[SENSITIVE_COL].value_counts(normalize=True)
    distances = []
    for _, group in valid.groupby(QI_COLS, dropna=False, observed=True):
        distances.append(categorical_distance(group[SENSITIVE_COL].value_counts(normalize=True), global_dist))
    violating = sum(distance > t for distance in distances)
    return {
        "t_value": t,
        "total_classes": len(distances),
        "violating_classes": violating,
        "t_satisfied": bool(violating == 0),
        "max_emd_distance": round(max(distances), 4),
        "t_satisfaction_%": round((len(distances) - violating) / len(distances) * 100, 2),
    }


def main() -> pd.DataFrame:
    from quasi_identifier_analysis import compute_prosecutor_risk, compute_rrr, load_data

    for path in ("data/processed", "outputs/tables", "outputs/charts"):
        os.makedirs(path, exist_ok=True)
    df = load_data()
    rows = []
    for k in K_VALUES:
        anon, _ = apply_k_anonymity(df, k)
        anon, suppressed = enforce_l_diversity(anon, l=2)
        if k >= 5:
            anon, suppressed = enforce_t_closeness(anon, t=0.3)
        anon.to_csv(f"data/processed/patients_k{k}.csv", index=False)
        valid = anon[anon[SENSITIVE_COL] != "*"]
        l2, l3 = check_l_diversity(anon, 2), check_l_diversity(anon, 3)
        t02, t03 = check_t_closeness(anon, 0.2), check_t_closeness(anon, 0.3)
        rows.append({
            "k": k,
            "Records_Kept": len(valid),
            "Records_Suppressed": suppressed,
            "Suppression_%": round(suppressed / len(df) * 100, 2),
            "NCP": compute_ncp(df, anon),
            "RRR_After": round(compute_rrr(valid, QI_COLS), 4),
            "Prosecutor_Risk": round(compute_prosecutor_risk(valid, QI_COLS), 4),
            "l2_satisfied": l2["l_satisfied"],
            "l3_satisfied": l3["l_satisfied"],
            "l2_satisfaction_%": l2["l_satisfaction_%"],
            "t02_satisfied": t02["t_satisfied"],
            "t03_satisfied": t03["t_satisfied"],
            "t03_satisfaction_%": t03["t_satisfaction_%"],
        })
    results = pd.DataFrame(rows)
    results.to_csv("outputs/tables/02_kanon_results.csv", index=False)
    print(tabulate(results, headers="keys", tablefmt="grid", showindex=False))

    fig, axes = plt.subplots(1, 3, figsize=(16, 5))
    axes[0].plot(results["k"], results["RRR_After"], "o-", color="#c0392b")
    axes[0].set(xlabel="k", ylabel="RRR", title="Re-identification Risk")
    axes[1].plot(results["k"], results["NCP"], "s-", color="#2980b9")
    axes[1].set(xlabel="k", ylabel="NCP", title="Information Loss")
    axes[2].bar(results["k"].astype(str), results["Suppression_%"], color="#f39c12")
    axes[2].set(xlabel="k", ylabel="Suppressed (%)", title="Suppression")
    for axis in axes:
        axis.grid(alpha=0.25)
    fig.suptitle("k-Anonymity Privacy-Utility Trade-off", fontweight="bold")
    fig.tight_layout()
    fig.savefig("outputs/charts/02_kanon_tradeoff.png", dpi=180, bbox_inches="tight")
    plt.close(fig)
    return results


if __name__ == "__main__":
    main()
